### ISSUE TITLE
Support Lenovo IdeaPad Flex 5 15ALC05

### ISSUE THREAD

**Issue by LaneDNickson** [0xless/battmngr#10]
- Model: 15ALC05
- System Product Name: 82HV
- I am not sure how to obtain calls/values for battery related operations but could do so with some guidance. Currently running Ubuntu 21.04 LTS.

**Comment by 0xless** [comment]
Hi, thanks for showing interest in this project.
I suggest you try different calls you can find in the JSON file in the experimental_support branch to see what works and what doesn't.

I never tried figuring out ACPI calls values, but it should be possible using official Lenovo Vantage software on Windows and sniffing the calls. If you figure out a reliable way to do that, I'd gladly add a guide to the repo.
