### ISSUE TITLE
Support for Legion 5 15ARH05

### ISSUE THREAD

**Issue by pm4rcin** [0xless/battmngr#7]
Hi, in my laptop I can change rapid charge and conservation mode with your script without problem. However I can't change the performance from Intelligent Cooling to any other. Since I discovered ability to change that settings after a year without using Windows up to today I thought these are Win-only features. So if you could help me identify my bits needed for it to work I'd be very happy. It's really strange all these string combinations. :)
EDIT: It could be that my laptop doesn't support changing performance modes. From tlp:
```fish
+++ Battery Care
Plugin: lenovo
Supported features: charge threshold
Driver usage:
* vendor (ideapad_laptop) = active (charge threshold)
Parameter value range:
* STOP_CHARGE_THRESH_BAT0: 0(off), 1(on) -- battery conservation mode

/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode = 0 (100%)
```

**Comment by 0xless** [comment]
Hi, thanks for the interest in this project.
I've had similar reports from other owners of Legion 5 and Ideapad Gaming 3.

Sadly there are no known ACPI calls to change performance modes for your laptop at the moment.

If you really want to help, you could try monitoring the ACPI calls made through Lenovo Vantage and report here the results.
I haven't really tried this (since I don't use windows at all), but it should theoretically work!

**Comment by pm4rcin** [comment]
Do you know how could I do that since I have no experience with Windows ACPI?

**Comment by pm4rcin** [comment]
Opensuse tumbleweed livecd kde has the fn+Q working OOTB. The color of power button changes. I'll try to find information how they achieved that.

**Comment by ayushjaipuriyar** [comment]
> Opensuse tumbleweed livecd kde has the fn+Q working OOTB. The color of power button changes. I'll try to find information how they achieved that.

I think thats because of the fact that fn+q is binded by the motherboard itself , in xev fn+q shows as xf86launch4.
I am using the same to call a rofi script that sets ryzenadj.

**Comment by pm4rcin** [comment]
@ayushjaipuriyar you're right, I probably had some shortcut conflict or something because it now works normally.
@0xless so regarding my laptop the battery conservation could be enabled with the sysfs I posted, rapid charge works with the same ACPI call as yours. And because fn+Q for switching modes works I don't really need that much to find acpi calls.

**Comment by pm4rcin** [comment]
Just wanted to share that as of https://github.com/johnfanv2/LenovoLegionLinux/commit/51526051bfd68155d398296fc1aedc2088864e2b I'm able to switch power modes with `powerprofilesctl` not needing `battmngr`. :) I have asked the developer of that project if he could make rapid charge be available via sysfs or smth like that. I'm waiting for response here https://github.com/antony-jr/lenovo-legion5-15arh05-scripts/issues/8#issuecomment-1500374856. @0xless I'm not sure if I should close the issue or leave it open?

**Comment by 0xless** [comment]
@pm4rcin please make sure that support for your laptop in `powerprofilesctl` works correctly before closing the issue.

There is no easy way to support many laptop models with the approach `battmngr` uses. If `battmngr` can't provide support for a specific laptop, I would consider the issue closed as long as there's another working option.

Keep us posted!
